/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteShimiArgs } from "./DeleteShimiArgs";
import { ShimiFindManyArgs } from "./ShimiFindManyArgs";
import { ShimiFindUniqueArgs } from "./ShimiFindUniqueArgs";
import { Shimi } from "./Shimi";
import { ShimiService } from "../shimi.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Shimi)
export class ShimiResolverBase {
  constructor(
    protected readonly service: ShimiService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Shimi",
    action: "read",
    possession: "any",
  })
  async _shimisMeta(
    @graphql.Args() args: ShimiFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Shimi])
  @nestAccessControl.UseRoles({
    resource: "Shimi",
    action: "read",
    possession: "any",
  })
  async shimis(@graphql.Args() args: ShimiFindManyArgs): Promise<Shimi[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Shimi, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Shimi",
    action: "read",
    possession: "own",
  })
  async shimi(
    @graphql.Args() args: ShimiFindUniqueArgs
  ): Promise<Shimi | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Shimi)
  @nestAccessControl.UseRoles({
    resource: "Shimi",
    action: "delete",
    possession: "any",
  })
  async deleteShimi(
    @graphql.Args() args: DeleteShimiArgs
  ): Promise<Shimi | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
